### ISSUE TITLE
Linking fails

### ISSUE THREAD

**Issue by protheory8** [SuperTails/langcraft#1]
I tried building Langcraft both debug and release mode, but both builds failed.
```
ld.lld: error: undefined symbol: LLVMCreateMemoryBufferWithContentsOfFile
>>> referenced by langcraft_bin.cdl61r7q-cgu.0

ld.lld: error: undefined symbol: LLVMContextCreate
>>> referenced by langcraft_bin.cdl61r7q-cgu.0

ld.lld: error: undefined symbol: LLVMParseBitcodeInContext2
>>> referenced by langcraft_bin.cdl61r7q-cgu.0
```
I didn't include the entire output, but all undefined symbols start with `LLVM`.
I'm using Fedora 32 and I made sure to have `llvm`, `llvm-devel` and `llvm-libs` packages installed.

**Comment by playXE** [comment]
Not a dev of langcraft but I think Fedora by default installs LLVM 10 while llvm-ir crate uses LLVM 9, maybe you can try to somehow install llvm 9?

**Comment by protheory8** [comment]
I can install LLVM 9, but it seems like llvm-sys can't find it because llvm9.0 package has different names for each file. Currently I'm trying to install Ubuntu 19.10 in VM and compile it there.

**Comment by protheory8** [comment]
Yeah, it compiles fine on Ubuntu 19.10.

**Comment by SuperTails** [comment]
Looking at the [crates.io page](https://crates.io/crates/llvm-sys) for `llvm-sys` it seems like you can specify a path to use for your LLVM install (not clear on LLVM versioning but it seems like I should just set `LLVM_SYS_90_PREFIX`... somehow?). I'll see if I can get a Fedora Live USB or something working and work this out.

**Comment by SuperTails** [comment]
I've opened up a Fedora install, and I have `llvm-9.0-devel` and friends installed. Running:
```
LLVM_SYS_90_PREFIX=/usr/lib64/llvm-9.0 cargo build
```
Does in fact make llvm-sys build using the correct version. However, even so, the build still fails with the same link errors. I'm pretty confident it's using the correct version because I don't have any other versions installed (and if you don't specify the path, llvm-sys complains that it can't find anything, so clearly it must be using the provided variable).
So we're closer, maybe, but not quite there yet.

**Comment by SuperTails** [comment]
Wait, hold on, I think I've solved it: You may also need `llvm9.0-static` in order for the above to work.
So, to summarize:
  - Install `llvm9.0-devel llvm9.0-libs llvm9.0-static`
  - Run `LLVM_SYS_90_PREFIX=/usr/lib64/llvm9.0 cargo build`
And it should work. Try that on your install and if it works, then I'll see about adding that to the README

**Comment by protheory8** [comment]
Didn't really work for me, same errors.

**Comment by protheory8** [comment]
I didn't figure it out, but I guess it will work when the crate will upgrade to LLVM 10.
